### ISSUE TITLE
Why the item's text can not be select? I want a feature likes the picture: 

### ISSUE THREAD

**Issue by shatle** [ondras/my-mind#59] opened 2015-07-31 09:00 UTC
![v1](https://cloud.githubusercontent.com/assets/1129872/9003872/5a6d2532-37a4-11e5-98a0-0ce78a52187b.gif)

---------

I want to select item's text using mouse, and delete by keyboard. 
I test in a simple contenteditable element that should be work, but item's text.

Sorry, I am poor for the repo. Who can tell me the reason? Conflict with the MoveItem?

Thanks!

**Comment by ondras** [comment] 2015-08-01 20:57
This looks like a reasonable feature. I will have a look at the code to see how easily is this doable.

**Comment by ondras** [comment] 2015-08-02 18:57
Shall be fixed now. Please confirm if the issue is gone.

**Closed** 2015-08-02 18:56 UTC

**Comment by shatle** [comment] 2015-08-04 01:19
Good, Thanks!
