### ISSUE TITLE
I found backslash and  double quotes can't be loaded correctly

### ISSUE THREAD

**Issue by 52manhua** [ondras/my-mind#64] opened 2016-10-31 01:28 UTC
Just use this to test (Maybe there is more =( ):

```
{
    "root": {
        "id": "aivcrkya",
        "text": "My Mind Map",
        "layout": "map",
        "children": [
            {
                "id": "hop\"fea\"di",
                "text": "test",
                "side": "right"
            },
            {
                "id": "oyh\\qiaet",
                "text": "test",
                "side": "left"
            },
            {
                "id": "zaknezat",
                "text": "test3",
                "side": "right"
            }
        ]
    }
}
```

**Comment by ondras** [comment] 2016-10-31 09:42
What exactly is the problem? Your sample works for me. Is there any error reported? Can you paste it here or share a screenshot?

**Comment by 52manhua** [comment] 2016-11-01 07:11
@ondras 
![snipaste20161101_150432](https://cloud.githubusercontent.com/assets/20589746/19882008/5aa60e6e-a045-11e6-97f0-45d9536388bb.png)
the test file.

![snipaste20161101_150545](https://cloud.githubusercontent.com/assets/20589746/19882014/619d1b40-a045-11e6-81cd-824aaa40f82a.png)
And the result

**Comment by 52manhua** [comment] 2016-11-01 07:13
And the one I post at first:

![snipaste20161101_151201](https://cloud.githubusercontent.com/assets/20589746/19882065/c7489154-a045-11e6-9c31-d0db6dc773bc.png)

**Comment by ondras** [comment] 2016-11-01 07:45
This is not related to the JSON escaping at all.

My Mind uses file extension to determine file type (when loading stuff from local filesystem). The official file extension for native JSON files is `.mymind`. Your files are apparently named in a different way, so My Mind thinks they are just plain "text" files and uses a simple row-based parser to convert them to a mind map.

To fix this, just maintain a proper file extension on your file (also note that when saving, the `.mymind` extension is automatically added).

**Comment by 52manhua** [comment] 2016-11-01 08:19
@ondras you are right, it's a extension problem, 
The problem is when I load the json strings by code:

```
                var str=' <json datas string>';
                var json = MM.Format.JSON.from(delHtmlTag(str));
                var map = MM.Map.fromJSON(json);
                MM.App.setMap(map);
```

Any suggestion?  THX

**Comment by ondras** [comment] 2016-11-01 08:21
Your code looks okay. What exactly is inside `str` and what happens when you remove the `delHtmlTag` function?

**Comment by 52manhua** [comment] 2016-11-01 08:32
@ondras 

```
	function delHtmlTag(str){
        return str.replace(/<[^>]+>/g,"");
		}
```
it works right, whether use it or not the result is the same...

and the test data:
`var str='{"root": {"id": "kfcckldm","text": "My Mind Map","layout": "map","children": [{"id": "rsapsldh","text": "Alice \"OK\"<br>","side": "right"},{"id": "xsbcqdix","text": "\\my problem\\","side": "left"}]}}'`

and I get this:
![image](https://cloud.githubusercontent.com/assets/20589746/19883694/b69e4dd4-a050-11e6-9d2d-62f3121abaee.png)

**Comment by 52manhua** [comment] 2016-11-01 08:33
@ondras when del the \ and " 

`var str='{"root": {"id": "kfcckldm","text": "My Mind Map","layout": "map","children": [{"id": "rsapsldh","text": "Alice OK<br>","side": "right"},{"id": "xsbcqdix","text": "my problem","side": "left"}]}}';`

it's ok:
![image](https://cloud.githubusercontent.com/assets/20589746/19883747/f44255b8-a050-11e6-8aa6-aa8fbde46b44.png)

**Comment by ondras** [comment] 2016-11-01 09:52
Right. Those escape sequences are interpreted too early, when your `str` is being parsed. You should parse your data into JS structures first, doing string replacements later on individual members.

Doing string replacements on JSONified strings is wrong anyway: replacing `/<[^>]+>/g` would completely crash in certain scenarios:

```js
{ a: "a<b", b: "c>d"}
```

So converting to JS objects first and replacing its member later is a better approach anyway.

**Comment by 52manhua** [comment] 2016-11-02 01:33
@ondras 
I tried again to remove the delHtmltag(), the result is the same~
I think there is something else in the process of loading string, and I'm trying to seek it out

**Comment by 52manhua** [comment] 2016-11-02 03:29
After some tests, I found it's a JSON.parse problem,when translate ,the  \ is missing.
So I do some dirty replace to make the string work,like this:

`str=str.replace(/\\/g,"\\\\\\");`

But the problem is \" can't be repalce right.

Replace

**Comment by 52manhua** [comment] 2016-11-02 07:28
Because I use php to write the string, then I do it this way,
just work! although it's so perfact~

`preg_replace('/\\\\/','\\\\\\',$content);`

I think all that because I use the php to write javascript in html~

**Comment by ondras** [comment] 2016-11-02 07:32
Yes, this might work, but is a bad approach anyway. You will run into issues with your `delHtmltag` function later. While it works with your current input, it will fail badly with other mind maps (such as the one I posted earlier).

The correct way here is to parse the JSON first (either in PHP or JS, does not matter), **then** walk its structure and apply the `delHtmltag` to individual members. Either way, this is not a bug in My Mind, so I am closing the issue.

**Closed by ondras** 2016-11-02 07:32 UTC

**Comment by 52manhua** [comment] 2016-11-02 07:37
@ondras I use the php strip_tags()  to do the thing~
